### ISSUE TITLE
Explore Google Maps API

### ISSUE THREAD

**Issue by Caryndcarter** [linhng15/Extravaganza#9]

**Comment by 1jared123** [comment]
# I don't Wanna work!

**Comment by 1jared123** [comment]
```
<div> Run for it!! </div>

```

**Comment by 1jared123** [comment]
Do's | Do NOTS
------------ | -------------
Work hard | Complain all the time
Comments with your commits | just commit without letting everyone know what you did!

**Comment by 1jared123** [comment]
:bowtie:

**Comment by 1jared123** [comment]
:poop: :poop: :poop: :poop: :poop: :poop: :poop: :poop: :poop: :poop: :poop: :poop: :poop: :poop: :poop:

**Comment by 1jared123** [comment]
:trollface: :trollface: :trollface: :trollface:  :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface:

**Comment by 1jared123** [comment]
:shipit: :shipit: :shipit:

**Comment by 1jared123** [comment]
(ノಠ益ಠ)ノ彡┻━┻

(╯°□°）╯︵ ┻━┻
